#!/bin/bash

export LANG='en_US.UTF-8'
# set column width
COLUMNS=3
# colors
green="\e[1;32m"
red="\e[1;31m"
undim="\e[0m"
declare -A services
services["postgresql"]="PostgreSQL"
services["apache2"]="Apache"
services["ssh"]="SSH"
services["fail2ban"]="Fail2Ban"
# sort services
k=0
out=""
for i in "${!services[@]}"; do
	((k++))
    # color green if service is active, else red
    service_status=($(systemctl is-active "$i"))
    if [[ "${service_status}" == "active" ]]; then
        out+="${services[$i]}:,${green}▲${undim},"
    else
        out+="${services[$i]}:,${red}▼${undim},"
    fi
    # insert \n every $COLUMNS column
    if [ $((($k) % $COLUMNS)) -eq 0 ]; then
        out+="\n"
    fi
done
out+="\n"

printf "\nservices:\n"
printf "$out" | column -ts $',' | sed -e 's/^/  /'
# printf "$services"
